package com.summer.graduate.myEnum;

public enum RedisSystem {
	DEL, BGSAVE, CLIENTKILL, CLIENTLIST, CLIENTGETNAME, CLIENTSETNAME, CLUSTERSLOTS, TIME, CONFIGGET, CONFIGSET,
	CONFIGRESETSTAT, DBSIZE, FLUSHALL, INFO, LASTSAVE, SAVE, SHUTDOWN, SLAVEOF, SLOWLOG, SYNC, KEYS, TYPE
}
